### ISSUE TITLE
Not finding a valid connection string

### ISSUE THREAD

**Issue by nickyhajal** [juliusmarminge/t3-supaedge#5]
Hey!

I'm trying to integrate this with t3-turbo and I'm trying to connect from my local machine to a Supabase DB, but keep getting the following:

```
Internal error: VercelPostgresError: VercelPostgresError - 'invalid_connection_string': This connection string is meant to be used with a direct connection. Make sure to use a pooled connection string or try `createClient()` instead.
```

This is my `.env`, with `POSTGRES_URL` set to a supabase pooler url.

![CleanShot 2024-04-16 at 13 04 33](https://github.com/juliusmarminge/t3-supaedge/assets/1079625/547af411-14b2-42bc-a5d4-4296379a8dc5)

Here I am logging `process.env.POSTGRES_URL` in `packages/db/index.ts` just before `drizzle(sql, { schema });` as well as in `packages/api/src/trpc.ts` to confirm that it is properly set and available in both locations.

![CleanShot 2024-04-16 at 13 05 58](https://github.com/juliusmarminge/t3-supaedge/assets/1079625/5d2f878b-b74c-4307-be6f-ecf01caebb8b)

Any idea why `vercel/postgres` isn't finding the connection string or things it's not a pooler?

Thanks for help and work on this!

**Comment by juliusmarminge** [comment]
checkout the example env on how to format the stirng. you must have that query param to get around the pooler warning

**Comment by nickyhajal** [comment]
That'll do it! Thanks for the super quick reply!
